name: "[release] make helm chart"
on:
  workflow_dispatch:
jobs:
  dispatch_make_helm_chart:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        target: [ 'console', 'console-api', 'identity', 'secret', 'repository', 'plugin', 'config', 'inventory', 'monitoring', 'statistics', 'cost-analysis',  'notification', 'supervisor' ]
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      TAG: ${{ github.event.inputs.tag }}
    steps:
      - name: task
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: cloudforet-io/${{ matrix.target }}
          event-type: make_helm_chart

      - name: Sleep for 1 minutes
        uses: whatnick/wait-action@master
        with:
          time: '1m'
  notify_to_slack:
    if: github.repository_owner == 'cloudforet-io'
    needs: [ dispatch_make_helm_chart ]
    runs-on: ubuntu-latest
    steps:
      - name: Slack
        if: always()
        uses: 8398a7/action-slack@v3.2.0
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          author_name: Github Action Slack
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
